Repository visgl/deck.gl, pull requests merged in 2018-05, with the labels that each got.

#1758 Remove React checks in controller classes
  modules/core/src/core/controllers/map-controller.js
  modules/core/src/core/controllers/orbit-controller.js
Labels: chore

#1765 Deprecate the OrbitViewport class
  modules/core/src/core/controllers/orbit-controller.js
  modules/core/src/core/controllers/orbit-state.js
  modules/core/src/core/deprecated/orbit-viewport.js
  modules/core/src/core/index.js
  modules/core/src/core/views/orbit-view.js
  modules/core/src/core/views/orthographic-view.js
  modules/core/src/core/views/perspective-view.js
  modules/core/src/core/views/third-person-view.js
Labels: chore

#1763 Move deprecated viewports to deprecated folder
  docs/api-reference/deck.md
  docs/api-reference/first-person-viewport.md
  docs/api-reference/orthographic-viewport.md
  docs/api-reference/perspective-viewport.md
  docs/api-reference/third-person-viewport.md
  examples/layer-browser/src/app.js
  examples/website/plot/plot-layer/axes-layer.js
  examples/website/point-cloud-laz/worker/laz-perf.js
  modules/core/src/core-layers/geojson-layer/geojson.js
  modules/core/src/core/controllers/viewport-controls.js
  modules/core/src/core/deprecated/first-person-viewport.js
  modules/core/src/core/deprecated/orthographic-viewport.js
  modules/core/src/core/deprecated/perspective-viewport.js
  modules/core/src/core/deprecated/third-person-viewport.js
  modules/core/src/core/index.js
  package.json
  test/modules/experimental-layers/gpu-grid-aggregator.spec.js
  yarn.lock
Labels: chore

#1640 Orthographic support in WebMercatorViewport
  docs/advanced/views.md
  docs/api-reference/viewport.md
  modules/core/src/core/viewports/viewport.js
  modules/core/src/core/viewports/web-mercator-viewport.js
Labels: code, doc, enhancement

#1769 Remove obsolete MapController and OrbitController "proxy" classes
  docs/api-reference/map-state.md
  docs/api-reference/orbit-state.md
  examples/layer-browser/src/app.js
  modules/core/src/core/controllers/controller.js
  modules/core/src/core/controllers/first-person-controller.js
  modules/core/src/core/controllers/map-controller.js
  modules/core/src/core/controllers/map-controls.js
  modules/core/src/core/controllers/map-state.js
  modules/core/src/core/controllers/orbit-controller.js
  modules/core/src/core/controllers/orbit-state.js
  modules/core/src/core/index.js
  modules/core/src/core/lib/deck.js
  test/modules/lite/deckgl.spec.js
Labels: code

#1771 Controller cleanup
  modules/core/src/core/controllers/controller.js
  modules/core/src/core/lib/deck.js
Labels: code

#1778 Hook git push with browser based tests
  package.json
  yarn.lock
Labels: chore

#1781 fix the wrong blog link
  docs/roadmap.md
  docs/whats-new.md
  website/src/components/header.js
Labels: doc

#1785 Add rendering test for orthographic mode
  test/render/golden-images/hexagoncell-lnglat-64.png
  test/render/golden-images/hexagoncell-lnglat.png
  test/render/test-cases.js
Labels: test

#1798 Bug fixes
  modules/react/src/viewport-controller.js
  test/modules/imports-spec.js
Labels: code, test

#1791 RFC catalog reorganization
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v5.1/transition-interpolator-class-rfc.md
  dev-docs/RFCs/v6.0/gpu-screengrid-aggregation-rfc.md
  dev-docs/RFCs/v6.0/partial-updates-rfc.md
  dev-docs/RFCs/v6.0/per-view-controllers.md
  dev-docs/RFCs/vNext/expose-attribute-manager.md
  dev-docs/RFCs/vNext/new-layers-rfc.md
  dev-docs/RFCs/vNext/off-thread-attribute-generation-rfc.md
  dev-docs/RFCs/vNext/reduce-distribution-size-rfc.md
  dev-docs/RFCs/vNext/reduce-repo-size-rfc.md
  dev-docs/RFCs/vNext/render-layer-to-texture-rfc.md
  dev-docs/RFCs/vNext/view-state-rfc.md
Labels: chore

#1804 Fix assert import from missing dependency
  modules/core/src/lib/attribute.js
Labels: bug

#1803 Bump example dependency versions
  examples/experimental/bezier/package.json
  examples/get-started/pure-js-without-map/package.json
  examples/get-started/pure-js/package.json
  examples/get-started/react-browserify/package.json
  examples/get-started/react-webpack/package.json
  examples/get-started/react-without-map/package.json
  examples/layer-browser/package.json
  examples/website/3d-heatmap/package.json
  examples/website/arc/package.json
  examples/website/brushing/package.json
  examples/website/geojson/package.json
  examples/website/icon/package.json
  examples/website/line/package.json
  examples/website/plot/package.json
  examples/website/point-cloud-laz/package.json
  examples/website/point-cloud-ply/package.json
  examples/website/scatterplot/package.json
  examples/website/screen-grid/package.json
  examples/website/tagmap/package.json
  examples/website/text-layer/package.json
  examples/website/trips/package.json
Labels: chore

#1787 Break out ViewManager class from LayerManager.
  modules/core/src/lib/layer-manager.js
  modules/core/src/views/view-manager.js
  test/modules/core/views/index.js
  test/modules/core/views/view-manager.spec.js
Labels: chore

#1582 Dist Size Reduction: Remove default attribute updaters
  modules/core-layers/src/arc-layer/arc-layer.js
  modules/core-layers/src/grid-cell-layer/grid-cell-layer.js
  modules/core-layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/core-layers/src/icon-layer/icon-layer.js
  modules/core-layers/src/line-layer/line-layer.js
  modules/core-layers/src/point-cloud-layer/point-cloud-layer.js
  modules/core-layers/src/scatterplot-layer/scatterplot-layer.js
Labels: code, test

#1777 Async Props #1: Add ability to differentiate between actual and resolved values for async props.
  modules/core/src/lib/layer.js
  modules/core/src/lifecycle/create-props.js
Labels: code, enhancement

#1779 Async Props #2: Loading and shadowing in new ComponentState base class
  modules/core/src/lib/layer.js
  modules/core/src/lifecycle/component-state.js
  modules/core/src/lifecycle/create-props.js
  test/modules/core/lifecycle/component-state.spec.js
Labels: code

#1822 Unblock render tests
  test/render/test-cases.js
Labels: bug, chore

#1825 Enable example testing for "experimental" and "get-started" folders
  test/node-examples.js
  test/render/golden-images/examples/pure-js-without-map.png
  test/render/golden-images/examples/pure-js.png
  test/render/golden-images/examples/react-without-map.png
  test/render/golden-images/examples/scatterplot.png
Labels: test

#1834 Update layer browser
  examples/layer-browser/app.css
  examples/layer-browser/src/app.js
  examples/layer-browser/src/components/layer-controls.js
Labels: chore

#1841 Fix viewportChanged flag
  modules/core/src/lib/layer-manager.js
Labels: bug

#1851 Reduce React emphasis in docs.
  README.md
  docs/README.md
  docs/api-reference/layer.md
  docs/api-reference/web-mercator-viewport.md
  docs/contributing.md
  docs/developer-guide/attribute-management.md
  docs/developer-guide/controllers.md
  docs/get-started/using-layers.md
  website/contents/pages.js
Labels: chore, doc

#1699 Fix pixel to clipspace projection
  modules/core/src/shaderlib/project/project.glsl.js
  test/render/golden-images/text-layer.png
  test/render/test-cases.js
Labels: code

#1869 Ib/fix transpilation
  modules/core/.babelrc
  modules/experimental-layers/.babelrc
  modules/layers/.babelrc
  modules/lite/.babelrc
  modules/main/.babelrc
  modules/react/.babelrc
  modules/test-utils/.babelrc
Labels: bug, chore

#1872 Update TextLayer render test golden image
  test/render/golden-images/text-layer.png
Labels: bug

#1876 Fix scripting in 5.3-release
  modules/lite/webpack.config.js
Labels: bug
