Repository visgl/deck.gl, pull requests merged in 2018-04, with the labels that each got.

#1610 View doc updates
  docs/advanced/view-state.md
  docs/advanced/viewports.md
  docs/advanced/views.md
  docs/api-reference/first-person-view.md
  docs/api-reference/view.md
  docs/api-reference/viewport.md
Labels: doc

#1612 Make `View` and `Deck` classes into official exports
  dev-docs/RFCs/v5.0/purejs-standalone-rfc.md
  examples/experimental/js/carto/app.js
  examples/experimental/js/with-mapbox-map/app.js
  examples/experimental/js/without-map/app.js
  src/core/controllers/map-controller.js
  src/core/controllers/orbit-controller.js
  src/core/index.js
  src/core/utils/assert.js
  src/core/utils/math-utils.js
  src/index.js
  src/react/src/deckgl.js
  src/react/src/index.js
  src/react/src/map-controller.js
  src/react/src/orbit-controller.js
  src/test-utils/src/lifecycle-test.js
  src/test-utils/src/scene-renderer.js
  test/src/core/views/view.spec.js
Labels: chore

#1613 View improvements
  src/core/views/orbit-view.js
  src/core/views/orthographic-view.js
  src/core/views/view.js
Labels: chore

#1614 Viewport improvements
  src/core/viewports/orbit-viewport.js
  src/core/viewports/orthographic-viewport.js
  src/core/viewports/viewport.js
  src/core/viewports/web-mercator-viewport.js
Labels: enhancement

#1589 Update deck.gl whats new doc
  docs/developer-guide/building-apps.md
  docs/whats-new.md
  website/contents/pages.js
Labels: chore

#1617 GpuScreenGridLayer : RFC and Fixes
  dev-docs/RFCs/v6.0/gpu-screengrid-aggregation.md
  src/experimental-layers/src/utils/gpu-grid-aggregator.js
Labels: code, doc

#1615 Integrate the existing JS controllers into Deck component
  examples/layer-browser/src/app.js
  src/core/controllers/map-controller.js
  src/core/controllers/orbit-controller.js
  src/core/controllers/viewport-controls.js
  src/core/lib/deck.js
  src/core/views/orthographic-view.js
  src/core/views/view.js
Labels: chore

#1616 Update examples using new View classes and Deck/Controller integration
  examples/bezier/deckgl-overlay.js
  examples/experimental/orthographic-zooming/app.js
  examples/graph/deckgl-overlay.js
  examples/graph/package.json
  examples/graph/webpack.config.js
  examples/plot/app.js
  examples/plot/deckgl-overlay.js
  examples/plot/package.json
  examples/plot/webpack.config.js
  examples/point-cloud-laz/app.js
  examples/point-cloud-ply/app.js
  examples/svg-interoperability/app.js
  src/core/lib/deck.js
  src/index.js
Labels: code

#1622 WhatsNew: Add ScreenGrid Icon, fix doc link
  docs/whats-new.md
Labels: doc

#1633 Remove polyfill. Update test scripts
  aliases.js
  examples/graph/deckgl-overlay.js
  examples/plot/app.js
  examples/plot/deckgl-overlay.js
  package.json
  scripts/collect-metrics.sh
  src/bundle.js
  src/experimental-layers/package.json
  src/experimental-layers/test/node-dist.js
  src/experimental-layers/test/node.js
  src/react/package.json
  src/test-utils/package.json
  src/test-utils/test/test-browser.js
  yarn.lock
Labels: chore

#1632 Improve test script speed. Fix test-browser reliability
  index.html
  package.json
  test/bench/browser.js
  test/render/test-cases.js
  test/start.js
  test/test-browser.js
  test/webpack.config.js
  webpack.config.js
  yarn.lock
Labels: chore

#1634 Final immutable removal
  examples/layer-browser/src/app.js
  examples/layer-browser/src/examples/core-layers.js
  examples/layer-browser/src/examples/experimental-layers.js
  examples/layer-browser/src/examples/infovis-layers.js
  examples/layer-browser/src/immutable-data-samples.js
  package.json
  test/render/test-cases.js
  yarn.lock
Labels: chore

#1635 Fix render tests by temporarily reverting the new orthographic map projection support
  src/core/viewports/web-mercator-viewport.js
Labels: bug

#1636 Introduce babel 7
  .babelrc
  .gitattributes
  package.json
  scripts/collect-metrics.sh
  yarn.lock
Labels: chore

#1638 Fix orthographic viewport
  examples/webpack.config.local.js
  src/core/views/orthographic-view.js
Labels: bug

#1628 Clean up LayerManager context handling
  src/core/lib/layer-manager.js
  src/core/lib/layer.js
Labels: chore

#1642 Quick Fix for `without-map` example
  examples/without-map/app.js
Labels: bug

#1645 fix text layer issue on windows
  src/core-layers/text-layer/text-layer.js
Labels: code

#1647 fix bench browser test
  package.json
  test/start.js
  test/webpack.config.js
Labels: chore

#1648 Bump example package.json to make it clear these are for future release
  examples/3d-heatmap/package.json
  examples/arc/package.json
  examples/bezier/package.json
  examples/brushing/package.json
  examples/experimental/js/with-mapbox-map/package.json
  examples/experimental/multi-viewport/package.json
  examples/experimental/orthographic-zooming/package.json
  examples/experimental/viewport-transitions-flyTo/package.json
  examples/experimental/viewport-transitions/package.json
  examples/geojson/package.json
  examples/graph/package.json
  examples/icon/package.json
  examples/line/package.json
  examples/plot/package.json
  examples/point-cloud-laz/package.json
  examples/point-cloud-ply/package.json
  examples/scatterplot/package.json
  examples/screen-grid/package.json
  examples/svg-interoperability/package.json
  examples/test-utils/package.json
  examples/test/tree-shaking/package.json
  examples/trips/package.json
  examples/wip/attribute-transition/package.json
  examples/without-map/package.json
Labels: chore

#1649 Bump examples to 5.2 alpha versions
  examples/3d-heatmap/package.json
  examples/arc/package.json
  examples/bezier/package.json
  examples/brushing/package.json
  examples/experimental/js/with-mapbox-map/package.json
  examples/experimental/multi-viewport/package.json
  examples/experimental/orthographic-zooming/package.json
  examples/experimental/viewport-transitions-flyTo/package.json
  examples/experimental/viewport-transitions/package.json
  examples/geojson/package.json
  examples/graph/package.json
  examples/icon/package.json
  examples/line/package.json
  examples/plot/package.json
  examples/point-cloud-laz/package.json
  examples/point-cloud-ply/package.json
  examples/scatterplot/package.json
  examples/screen-grid/package.json
  examples/svg-interoperability/package.json
  examples/test-utils/package.json
  examples/test/tree-shaking/package.json
  examples/text-layer/package.json
  examples/trips/package.json
  examples/wip/attribute-transition/package.json
  examples/without-map/package.json
Labels: chore

#1389 Deck Component: auto resize handling
  examples/layer-browser/src/app.js
  examples/scatterplot/app.js
  examples/scatterplot/deckgl-overlay.js
  package.json
  src/core/lib/deck.js
  src/core/lib/layer-manager.js
  src/react/src/deckgl.js
  src/test-utils/src/scene-renderer.js
Labels: code

#1663 fix bootstrap
  scripts/bootstrap.sh
Labels: chore

#1664 add linter to ci test
  package.json
Labels: chore

#1644 fix example testing
  examples/test/golden-images/geojson.png
  examples/test/golden-images/tagmap.png
Labels: chore

#1665 Fix website dependencies
  website/package.json
  website/webpack.config.js
Labels: chore

#1678 add text-layer screenshot to what's new
  docs/whats-new.md
  examples/text-layer/app.js
  examples/text-layer/deckgl-overlay.js
Labels: chore

#1639 use fetch instead of d3-request/json in examples
  examples/3d-heatmap/package.json
  examples/arc/app.js
  examples/arc/package.json
  examples/bezier/package.json
  examples/brushing/app.js
  examples/brushing/package.json
  examples/geojson/app.js
  examples/geojson/package.json
  examples/graph/package.json
  examples/icon/app.js
  examples/icon/package.json
  examples/layer-browser/package.json
  examples/line/app.js
  examples/line/package.json
  examples/scatterplot/app.js
  examples/scatterplot/package.json
  examples/screen-grid/app.js
  examples/screen-grid/package.json
  examples/svg-interoperability/package.json
  examples/tagmap/app.js
  examples/tagmap/package.json
  examples/text-layer/app.js
  examples/text-layer/package.json
  examples/trips/app.js
  examples/trips/package.json
Labels: chore

#1681 replace deck.gl-layers with @deck.gl/experimental-layers
  examples/bezier/deckgl-overlay.js
  examples/layer-browser/package.json
  examples/layer-browser/src/examples/experimental-layers.js
  examples/test-utils/webpack.config.js
Labels: chore

#1682 update whats new
  docs/whats-new.md
Labels: chore

#1674 Move "fragile" carto pure JS example to wip folder
  test/apps/wip/carto/README.md
  test/apps/wip/carto/app.js
  test/apps/wip/carto/index.html
  test/apps/wip/carto/package.json
  test/apps/wip/carto/time-sliced-scatterplot-layer/time-sliced-scatterplot-layer-fragment.glsl.js
  test/apps/wip/carto/time-sliced-scatterplot-layer/time-sliced-scatterplot-layer-vertex-64.glsl.js
  test/apps/wip/carto/time-sliced-scatterplot-layer/time-sliced-scatterplot-layer-vertex.glsl.js
  test/apps/wip/carto/time-sliced-scatterplot-layer/time-sliced-scatterplot-layer.js
  test/apps/wip/carto/utils/carto-torque-utils.js
  test/apps/wip/carto/webpack.config.js
Labels: chore

#1686 v5.2.0-beta.1
  CHANGELOG.md
  lerna.json
  modules/core/package.json
  yarn.lock
Labels: chore

#1698 Fix font bounding box
  modules/core/src/core-layers/text-layer/font-atlas.js
  modules/core/src/core-layers/text-layer/text-layer.js
  test/render/golden-images/text-layer.png
Labels: bug

#1707 Fix inverted FirstPersonView
  docs/advanced/view-state.md
  examples/layer-browser/src/app.js
  modules/core/src/core/viewports/viewport.js
Labels: bug

#1708 Bump math.gl
  modules/core/package.json
  yarn.lock
Labels: chore

#1713 handle review feedback for useDevicePixels
  modules/core/src/core/lib/deck.js
  modules/core/src/core/lib/layer-manager.js
Labels: code

#1718 Update test-utils website pages
  docs/api-reference/test-utils/render-test.md
  docs/api-reference/test-utils/test-layer.md
  docs/developer-guide/testing/README.md
  docs/developer-guide/testing/testing.md
  docs/developer-guide/testing/using-with-unit-test-frameworks.md
  website/contents/pages.js
Labels: chore

#1720 more doc fix for test-utils
  docs/api-reference/test-utils/render-test.md
  docs/developer-guide/testing/README.md
Labels: chore

#1723 Fix multi-viewport test app
  test/apps/multi-viewport/app.js
  test/apps/multi-viewport/index.html
Labels: bug, chore

#1724 Move wind and graph examples to showcases
  examples/layer-browser/src/app.js
  examples/website/plot/plot-layer/axes-layer.js
  examples/website/point-cloud-laz/worker/laz-perf.js
  modules/core/src/core-layers/geojson-layer/geojson.js
  modules/core/src/core/controllers/viewport-controls.js
  showcases/ascii/README.md
  showcases/ascii/app.js
  showcases/ascii/ascii-layer/ascii-filter.js
  showcases/ascii/ascii-layer/ascii-layer.js
  showcases/ascii/ascii-layer/utils.js
  showcases/ascii/components/constants.js
  showcases/ascii/components/control-panel.js
  showcases/ascii/index.html
  showcases/ascii/package.json
  showcases/ascii/webpack.config.js
  showcases/graph/README.md
  showcases/graph/app.css
  showcases/graph/app.js
  showcases/graph/data/node-icon-atlas.json
  showcases/graph/data/node-icon-atlas.png
  showcases/graph/deckgl-overlay.js
  showcases/graph/graph-layer/adaptor/graph-SNAP.js
  showcases/graph/graph-layer/adaptor/graph-basic.js
  showcases/graph/graph-layer/adaptor/graph-flare.js
  showcases/graph/graph-layer/graph-layer.js
  showcases/graph/graph-layer/graph-layout-layer.js
  showcases/graph/graph-layer/layout/layout-d3.js
  showcases/graph/index.html
  showcases/graph/package.json
  showcases/graph/webpack.config.js
  showcases/wind/README.md
  showcases/wind/package.json
  showcases/wind/src/app.js
  showcases/wind/src/control-panel.js
  showcases/wind/src/defaults.js
  showcases/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer-fragment.glsl.js
  showcases/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer-vertex.glsl.js
  showcases/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer.js
  showcases/wind/src/layers/delaunay-interpolation/delaunay-interpolation-fragment.glsl.js
  showcases/wind/src/layers/delaunay-interpolation/delaunay-interpolation-vertex.glsl.js
  showcases/wind/src/layers/delaunay-interpolation/delaunay-interpolation.js
  showcases/wind/src/layers/elevation-layer/elevation-layer-fragment.glsl.js
  showcases/wind/src/layers/elevation-layer/elevation-layer-vertex.glsl.js
  showcases/wind/src/layers/elevation-layer/elevation-layer.js
  showcases/wind/src/layers/elevation-layer/grid-geometry.js
  showcases/wind/src/layers/particle-layer/particle-layer-fragment.glsl.js
  showcases/wind/src/layers/particle-layer/particle-layer-vertex.glsl.js
  showcases/wind/src/layers/particle-layer/particle-layer.js
  showcases/wind/src/layers/particle-layer/transform-feedback-vertex.glsl.js
  showcases/wind/src/layers/wind-layer/wind-layer-fragment.js
  showcases/wind/src/layers/wind-layer/wind-layer-vertex.js
  showcases/wind/src/layers/wind-layer/wind-layer.js
  showcases/wind/src/shaderlib/fs-fp32/fs-fp32.js
  showcases/wind/src/shaderlib/fs-lighting/fs-lighting.js
  showcases/wind/src/shaderlib/fs-project/fs-project.js
  showcases/wind/src/utils/load-data.js
  showcases/wind/src/wind-demo.js
  showcases/wind/static/index.html
  showcases/wind/static/style.css
  showcases/wind/webpack.config.js
Labels: chore

#1725 Upgrade point cloud LAZ to webpack 4
  examples/website/point-cloud-laz/package.json
  examples/website/point-cloud-laz/webpack.config.js
Labels: chore

#1726 fix vis academy page on website
  docs/get-started/vis-academy.md
Labels: chore

#1727 fix example test
  examples/website/brushing/package.json
  test/node-examples.js
Labels: chore

#1731 View documentation updates.
  docs/advanced/views.md
  docs/api-reference/first-person-view.md
  docs/api-reference/map-view.md
  docs/api-reference/orthographic-view.md
  docs/api-reference/perspective-view.md
  docs/api-reference/test-utils/test-layer.md
  docs/api-reference/third-person-view.md
  docs/api-reference/view.md
  docs/whats-new.md
  modules/core/src/core/views/perspective-view.js
  modules/core/src/core/views/view.js
Labels: chore, doc

#1734 Fix bad links on website
  docs/advanced/view-state.md
  docs/advanced/viewports.md
  docs/advanced/views.md
  docs/api-reference/layer.md
  docs/api-reference/web-mercator-viewport.md
  docs/get-started/interactivity.md
  docs/get-started/using-layers.md
  docs/get-started/using-with-react.md
  docs/whats-new.md
  website/contents/pages.js
  website/src/components/markdown-page.js
Labels: chore

#1737 Make DeckGL doc refer to Deck docs
  docs/api-reference/deck.md
  docs/api-reference/react/deckgl.md
Labels: chore, doc

#1747 Update picking RFC
  dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md
Labels: chore

#1750 Smaller viewState related fixes
  modules/core/src/core/controllers/viewport-controls.js
  modules/core/src/core/lib/layer-manager.js
  modules/react/src/deckgl.js
Labels: chore
