Repository visgl/deck.gl, pull requests merged in 2018-08, with the labels that each got.

#2146 Bump luma.gl and math.gl versions to latest alpha
  modules/core/package.json
Labels: chore

#2149 Update unit and render tests
  test/modules/core/experimental/utils/gpu-grid-aggregator.spec.js
  test/modules/core/experimental/utils/grid-aggregation-utils.spec.js
  test/render/test-cases.js
Labels: chore

#2153 RFC updates
  dev-docs/RFCs/v6.1/json-layers-rfc.md
  dev-docs/RFCs/v6.1/layer-group-and-operation-rfc.md
  dev-docs/RFCs/v6.x/property-animation-rfc.md
  docs/developer-guide/json/configuring-json-layers.md
  docs/developer-guide/json/using-json-api.md
  modules/core/src/lib/init.js
  yarn.lock
Labels: chore

#2156 Minor cleanup
  dev-docs/RFCs/v5.0/purejs-standalone-rfc.md
  docs/layers/arc-layer.md
  docs/layers/geojson-layer.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/hexagon-cell-layer.md
  docs/layers/hexagon-layer.md
  docs/layers/icon-layer.md
  docs/layers/line-layer.md
  docs/layers/path-layer.md
  docs/layers/point-cloud-layer.md
  docs/layers/polygon-layer.md
  docs/layers/scatterplot-layer.md
  docs/layers/screen-grid-layer.md
  docs/layers/solid-polygon-layer.md
  docs/layers/text-layer.md
  modules/core/README.md
  modules/core/src/lib/deck.js
  modules/experimental-layers/README.md
  modules/layers/README.md
  modules/main/README.md
  modules/react/README.md
  modules/test-utils/README.md
  test/modules/core/experimental/utils/gpu-grid-aggregator.spec.js
  test/modules/core/experimental/utils/grid-aggregation-utils.spec.js
  test/modules/index.js
  test/modules/layers/core-layers.spec.js
  test/modules/layers/geojson-layer.spec.js
  test/modules/layers/geojson.spec.js
  test/modules/layers/grid-cell-layer.spec.js
  test/modules/layers/grid-layer.spec.js
  test/modules/layers/hexagon-cell-layer.spec.js
  test/modules/layers/hexagon-layer.spec.js
  test/modules/layers/index.js
  test/modules/layers/polygon-layer.spec.js
  test/modules/layers/polygon-tesselation.spec.js
  test/start.js
  yarn.lock
Labels: chore

#2157 Build fixes
  modules/core/package.json
  modules/experimental-layers/README.md
  modules/lite/package.json
  modules/test-utils/package.json
Labels: chore

#2163 RFC/Roadmap Overhaul
  dev-docs/RFC-GUIDELINES.md
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v5.0/multi-viewport-rfc.md
  dev-docs/RFCs/v5.0/viewport-transition-rfc.md
  dev-docs/RFCs/v5.1/attribute-transition-rfc.md
  dev-docs/RFCs/v5.2/unified-32-and-64-bit-project-api-rfc.md
  dev-docs/RFCs/v5.2/view-class-rfc.md
  dev-docs/RFCs/v5.3/async-props-rfc.md
  dev-docs/RFCs/v5.3/attribute-buffer-rfc.md
  dev-docs/RFCs/v5.3/constant-accessor-rfc.md
  dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md
  dev-docs/RFCs/v6.0/gpu-screengrid-aggregation-rfc.md
  dev-docs/RFCs/v6.0/per-view-controllers-rfc.md
  dev-docs/RFCs/v6.0/react-api-rfc.md
  dev-docs/RFCs/v6.1/improved-lnglat-projection-rfc.md
  dev-docs/RFCs/v6.1/json-layers-rfc.md
  dev-docs/RFCs/v6.1/view-class-extension-rfc.md
  dev-docs/RFCs/v6.x/binary-data-rfc.md
  dev-docs/RFCs/v6.x/layer-group-and-operation-rfc.md
  dev-docs/RFCs/v6.x/project-unproject-rfc.md
  dev-docs/RFCs/v6.x/property-animation-rfc.md
  dev-docs/RFCs/v6.x/property-transition-rfc.md
  dev-docs/roadmaps/layers-roadmap.md
Labels: chore

#2166 fix icon layer rendering test and avoid test report duplication
  modules/test-utils/src/scene-renderer.js
  test/render/test-cases.js
Labels: test

#2158 PATCH (v6.0.x): Bump probe.gl version to avoid issues with changed webpack behavior
  modules/core/package.json
  modules/test-utils/package.json
Labels: bug, chore

#2174 Bump dependency
  examples/experimental/json-layers/webpack.config.js
  modules/core/package.json
  modules/test-utils/package.json
  test/apps/attribute-transition/package.json
  test/apps/multi-viewport/package.json
  test/apps/orthographic-zooming/package.json
  test/apps/tree-shaking/package.json
  yarn.lock
Labels: chore

#2164 Roadmap updates
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v6.x/property-animation-rfc.md
  dev-docs/roadmaps/animation-roadmap.md
  dev-docs/roadmaps/layers-roadmap.md
  dev-docs/roadmaps/performance-roadmap.md
Labels: chore

#2175 Propose: Move TripsLayer to experimental-layers
  examples/website/trips/app.js
  modules/experimental-layers/src/index.js
  modules/experimental-layers/src/trips-layer/README.md
  modules/experimental-layers/src/trips-layer/index.js
  modules/experimental-layers/src/trips-layer/trips-layer-fragment.glsl.js
  modules/experimental-layers/src/trips-layer/trips-layer-vertex.glsl.js
  modules/experimental-layers/src/trips-layer/trips-layer.js
Labels: chore

#2183 lighting module initial roadmap
  dev-docs/roadmaps/lighting-roadmap.md
Labels: chore

#2206 Update docs for new projection mode
  docs/api-reference/web-mercator-viewport.md
  docs/developer-guide/64-bits.md
  docs/developer-guide/coordinate-systems.md
  docs/developer-guide/performance.md
  docs/developer-guide/writing-shaders.md
  docs/layers/arc-layer.md
  docs/layers/contour-layer.md
  docs/layers/geojson-layer.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/hexagon-cell-layer.md
  docs/layers/hexagon-layer.md
  docs/layers/icon-layer.md
  docs/layers/line-layer.md
  docs/layers/path-layer.md
  docs/layers/point-cloud-layer.md
  docs/layers/polygon-layer.md
  docs/layers/scatterplot-layer.md
  docs/layers/solid-polygon-layer.md
  docs/layers/text-layer.md
  docs/shader-modules/project.md
  docs/whats-new.md
Labels: doc

#2213 Expose more internals (as experimental exports) (#1921)
  modules/layers/src/index.js
  modules/layers/src/path-layer/path-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
Labels: chore

#2211 Use shaderCoordinateSystem
  modules/core/src/lib/constants.js
  modules/core/src/lib/layer.js
  modules/core/src/shaderlib/project/constants.js
  modules/core/src/shaderlib/project/project.glsl.js
  modules/core/src/shaderlib/project/viewport-uniforms.js
  test/modules/core/lib/layer.spec.js
Labels: code

#2229 Undo Y-reversal hack for Mesh-Layer
  modules/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js
Labels: bug

#2236 Add publish-guideline
  dev-docs/PUBLISH-CHECKLIST.md
Labels: chore

#2244 Safari fixes
  .eslintignore
  .prettierignore
  examples/layer-browser/package.json
  examples/webpack.config.local.js
  modules/core/package.json
  modules/experimental-layers/package.json
  modules/json/package.json
  modules/layers/package.json
  modules/react/package.json
  modules/test-utils/package.json
  package.json
  yarn.lock
Labels: chore
