Repository visgl/deck.gl, pull requests merged in 2018-02, with the labels that each got.

#1412 Fix log typo
  src/core/lib/draw-layers.js
Labels: bug

#1424 Catch exception in rendering test
  test/rendering-test/node-rendering.js
Labels: bug

#1426 npm run clean-modules script
  .prettierignore
  package.json
Labels: chore

#1445 update using-with-react.md with workable example code
  docs/get-started/using-with-react.md
Labels: docs

#1446 Change "Attribute Transitions" to "Layer Transitions"
  docs/whats-new.md
Labels: docs

#1451 Fix devicePixelRatio uniform
  src/core/lib/draw-layers.js
  src/core/shaderlib/project/viewport-uniforms.js
Labels: bug

#1442 Remove `get` usage in geojson layer
  src/core-layers/geojson-layer/geojson-layer.js
  src/core-layers/geojson-layer/geojson.js
  test/src/core-layers/geojson.spec.js
Labels: chore

#1462 Fix wrong image links in website
  docs/advanced/64-bits.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/hexagon-cell-layer.md
  docs/layers/hexagon-layer.md
  website/src/components/markdown-page.js
Labels: doc

#1463 Change default 'extruded' to be 'false' in hexagon-layer.md
  docs/layers/hexagon-layer.md
Labels: doc

#1465 Update docs for layer transitions.
  docs/api-reference/attribute-manager.md
  docs/api-reference/layer.md
  docs/whats-new.md
Labels: doc

#1466 Update README.md and package.json to reflect latest luma.gl
  README.md
  package.json
  yarn.lock
Labels: chore

#1460 Fix viewportChanged flag
  src/core/lib/layer-manager.js
Labels: bug

#1461 Fix layer-browser hot reload
  examples/layer-browser/src/app.js
  examples/layer-browser/src/index.js
  examples/layer-browser/webpack.config.js
Labels: chore

#1469 Fix link rewrite in website
  website/contents/pages.js
Labels: code

#1472 Fix plot demo on website
  website/src/components/demos/plot-demo.js
Labels: code

#1475 Do not pick when dragging
  src/core/lib/layer-manager.js
Labels: code

#1478 Improve point-cloud-laz example by skipping rendering until data loaded
  examples/point-cloud-laz/app.js
Labels: chore

#1482 [Website] Render nested categories in side bar
  website/contents/pages.js
  website/src/components/table-of-contents.js
  website/src/stylesheets/_gallery.scss
Labels: code

#1486 Update golden images
  test/render/golden-images/geojson-extruded-lnglat.png
  test/render/golden-images/grid-lnglat.png
  test/render/golden-images/gridcell-lnglat.png
  test/render/golden-images/hexagon-lnglat.png
  test/render/golden-images/hexagoncell-lnglat.png
  test/render/golden-images/pointcloud-lnglat-64.png
  test/render/golden-images/pointcloud-lnglat.png
  test/render/golden-images/pointcloud-meter.png
Labels: test

#1487 Fix layer browser disappearing controls
  examples/layer-browser/src/app.js
Labels: chore

#1480 [website] redirect to new blog
  website/src/components/header.js
Labels: doc
