Repository visgl/deck.gl, pull requests merged in 2018-07, with the labels that each got.

#2005 fix point cloud examples
  examples/website/point-cloud-laz/app.js
  examples/website/point-cloud-ply/app.js
Labels: code

#2016 Fix: Trigger trips-layer animation
  examples/website/trips/app.js
Labels: bug

#2014 fix the scale and point size for point cloud examples
  examples/website/point-cloud-laz/app.js
  examples/website/point-cloud-ply/app.js
Labels: code

#2045 add doc for OrbitView
  docs/api-reference/orbit-view.md
  website/contents/pages.js
Labels: doc

#2083 fix bad links on master
  docs/api-reference/attribute-manager.md
  docs/api-reference/composite-layer.md
  docs/api-reference/controller.md
  docs/api-reference/deck.md
  docs/api-reference/first-person-view.md
  docs/api-reference/internal/layer-manager.md
  docs/api-reference/layer.md
  docs/api-reference/map-controller.md
  docs/api-reference/orthographic-view.md
  docs/api-reference/perspective-view.md
  docs/api-reference/react/deckgl.md
  docs/api-reference/standalone/deckgl.md
  docs/api-reference/test-utils/render-test.md
  docs/api-reference/test-utils/scene-renderer.md
  docs/api-reference/test-utils/test-layer.md
  docs/api-reference/third-person-view.md
  docs/api-reference/view.md
  docs/api-reference/viewport.md
  docs/api-reference/web-mercator-viewport.md
  docs/get-started/getting-started.md
  docs/get-started/using-layers.md
  docs/get-started/using-standalone.md
  docs/get-started/using-with-mapbox-gl.md
  docs/layers/README.md
  docs/layers/arc-layer.md
  docs/layers/geojson-layer.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/hexagon-cell-layer.md
  docs/layers/hexagon-layer.md
  docs/layers/icon-layer.md
  docs/layers/line-layer.md
  docs/layers/path-layer.md
  docs/layers/point-cloud-layer.md
  docs/layers/polygon-layer.md
  docs/layers/scatterplot-layer.md
  docs/layers/screen-grid-layer.md
  docs/layers/solid-polygon-layer.md
  docs/layers/text-layer.md
Labels: chore

#2137 Remove mapbox wrapper from pure-js example
  examples/get-started/pure-js/app.js
  examples/get-started/pure-js/mapbox.js
Labels: chore

#2135 Fix solid-polygon-layer to work with new coordinate mode
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
Labels: bug

#2128 Orthographic view controller
  examples/experimental/bezier/app.js
  examples/experimental/bezier/deckgl-overlay.js
  examples/experimental/bezier/package.json
  examples/experimental/bezier/sample-graph.js
  examples/experimental/bezier/sample-graph.json
  modules/core/src/controllers/orthographic-controller.js
  modules/core/src/index.js
  modules/core/src/views/orthographic-view.js
Labels: enhancement
