Repository visgl/deck.gl, pull requests merged in 2018-06, with the labels that each got.

#1864 View Manager cleanup
  .eslintrc
  examples/experimental/bezier/app.js
  examples/website/3d-heatmap/app.js
  examples/website/arc/app.js
  examples/website/brushing/app.js
  examples/website/geojson/app.js
  examples/website/icon/app.js
  examples/website/line/app.js
  examples/website/plot/app.js
  examples/website/scatterplot/app.js
  examples/website/screen-grid/app.js
  examples/website/tagmap/app.js
  examples/website/text-layer/app.js
  examples/website/trips/app.js
  modules/core/src/lib/deck.js
  modules/core/src/views/view-manager.js
  modules/react/src/deckgl.js
  modules/react/src/utils/extract-jsx-layers.js
Labels: chore

#1878 Some example fixes
  examples/website/arc/app.js
  examples/website/icon/app.js
  modules/react/src/deckgl.js
  website/src/components/demos/icon-demo.js
Labels: bug

#1883 Fix whats-new layer demo urls.
  docs/whats-new.md
Labels: doc

#1884 Make sure website examples start locally
  examples/website/brushing/app.js
  examples/website/brushing/arc-brushing-layer/index.js
  examples/website/brushing/scatterplot-brushing-layer/index.js
  examples/website/geojson/app.js
  examples/website/line/app.js
  examples/website/scatterplot/app.js
Labels: bug

#1903 Disable failing rendertests for Intel GPU
  modules/test-utils/src/scene-renderer.js
  test/render/test-cases.js
Labels: test

#1915 Bench fixes
  modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
  test/bench/array-copy.bench.js
  test/bench/browser.js
  test/bench/gpu-grid-aggregator.bench.js
  test/bench/index.js
  test/bench/utils.bench.js
  test/start.js
Labels: bug

#1926 Move ViewManager out of LayerManager
  examples/layer-browser/src/app.js
  modules/core/src/lib/deck.js
  modules/core/src/lib/layer-manager.js
  modules/core/src/views/view-manager.js
  modules/react/src/deckgl.js
  modules/test-utils/src/lifecycle-test.js
  test/modules/core/lib/layer-manager.spec.js
  yarn.lock
Labels: chore, code

#1933 Linter only changes, no functional changes
  examples/experimental/bitmap/app.js
  examples/layer-browser/src/data-samples.js
  examples/layer-browser/src/examples/infovis-layers.js
  examples/layer-browser/src/utils/grid-aggregator.js
  examples/website/icon/app.js
  examples/website/plot/app.js
  examples/website/plot/plot-layer/surface-layer.js
  examples/website/point-cloud-laz/worker/laz-perf.js
  examples/website/tagmap/tagmap-layer/tagmap-wrapper.js
  examples/website/text-layer/app.js
  examples/website/trips/app.js
  modules/core/src/controllers/controller.js
  modules/core/src/controllers/first-person-controller.js
  modules/core/src/controllers/orbit-controller.js
  modules/core/src/deprecated/orbit-viewport.js
  modules/core/src/utils/bin-sorter.js
  modules/core/src/utils/scale-utils.js
  modules/core/src/views/orbit-view.js
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
  modules/experimental-layers/src/path-marker-layer/create-path-markers.js
  modules/layers/src/grid-layer/grid-aggregator.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/screen-grid-layer/screen-grid-layer.js
  modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
  modules/lite/test/index.js
  modules/test-utils/src/lifecycle-test.js
  modules/test-utils/src/luma.gl/gpgpu/diff-images.js
  modules/test-utils/src/luma.gl/io-basic/browser-request-file.js
  test/apps/attribute-transition/data-generator.js
  test/apps/carto-wip/utils/carto-torque-utils.js
  test/apps/multi-viewport/app.js
  test/apps/orthographic-zooming/app.js
  test/modules/core/lib/layer-manager.spec.js
Labels: chore

#1939 Fix path-marker-layer property passing
  examples/layer-browser/src/examples/experimental-layers.js
  modules/experimental-layers/src/path-marker-layer/path-marker-layer.js
  modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
Labels: P0, bug

#1941 Fix path-marker-layer property passing, and remove moduleParameters to fix offset coordinates
  examples/layer-browser/src/examples/experimental-layers.js
  modules/experimental-layers/src/path-marker-layer/path-marker-layer.js
  modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
Labels: bug

#1944 Disable 64 bit gpu aggregation test
  test/modules/experimental-layers/gpu-grid-aggregator.spec.js
Labels: chore

#1932 GPUScreenGridLayer: Add colorRange and colorDomain support.
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-fragment.glsl.js
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-vertex.glsl.js
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
Labels: enhancement

#1949 Lock prettier module versions, add linter changes (no functional changes)
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
  package.json
  yarn.lock
Labels: chore

#1928 Upgrade to luma v6
  docs/developer-guide/primitive-layers.md
  examples/experimental/bitmap/app.js
  examples/layer-browser/src/app.js
  examples/layer-browser/src/examples/experimental-layers.js
  examples/webpack.config.local.js
  examples/website/line/app.js
  examples/website/plot/plot-layer/axes-layer.js
  examples/website/plot/plot-layer/surface-layer.js
  examples/website/plot/plot-layer/utils.js
  examples/website/point-cloud-laz/app.js
  examples/website/text-layer/deckgl-overlay.js
  modules/core/package.json
  modules/core/src/experimental/reflection-effect/reflection-effect.js
  modules/core/src/lib/attribute-transition-manager.js
  modules/core/src/lib/attribute.js
  modules/core/src/lib/deck.js
  modules/core/src/lib/draw-layers.js
  modules/core/src/lib/init.js
  modules/core/src/lib/layer-manager.js
  modules/core/src/lib/layer.js
  modules/core/src/lib/seer-integration.js
  modules/core/src/utils/log.js
  modules/experimental-layers/src/bezier-curve-layer/bezier-curve-layer.js
  modules/experimental-layers/src/bitmap-layer/bitmap-layer.js
  modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
  modules/experimental-layers/src/mesh-layer/mesh-layer.js
  modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
  modules/experimental-layers/src/utils/gpu-grid-aggregator.js
  modules/layers/src/arc-layer/arc-layer.js
  modules/layers/src/grid-cell-layer/grid-cell-layer.js
  modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/layers/src/icon-layer/icon-layer.js
  modules/layers/src/line-layer/line-layer.js
  modules/layers/src/path-layer/path-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/scatterplot-layer/scatterplot-layer.js
  modules/layers/src/screen-grid-layer/screen-grid-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  modules/react/src/deckgl.js
  showcases/wind/src/layers/elevation-layer/elevation-layer.js
  showcases/wind/src/layers/elevation-layer/grid-geometry.js
  showcases/wind/src/layers/particle-layer/particle-layer.js
  showcases/wind/src/layers/wind-layer/wind-layer.js
  test/apps/sample-layers/bitmap-layer/bitmap-layer.js
  test/apps/sample-layers/enhanced-choropleth-layer/enhanced-choropleth-layer.js
  test/apps/sample-layers/label-layer/label-utils.js
  test/modules/core-layers/core-layers.spec.js
  test/modules/core/lib/attribute-manager.spec.js
  test/modules/core/lib/attribute-transition-manager.spec.js
  test/modules/core/lib/attribute.spec.js
  test/modules/experimental-layers/gpu-grid-utils.spec.js
  test/modules/imports-spec.js
  test/test-browser.js
  website/src/components/demos/plot-demo.js
  website/webpack.config.js
  yarn.lock
Labels: chore

#1963 Add needs64bitPositions() to Layer and use it in existing layers
  docs/whats-new.md
  modules/core/src/lib/layer.js
  modules/experimental-layers/src/mesh-layer/mesh-layer.js
  modules/layers/src/arc-layer/arc-layer.js
  modules/layers/src/grid-cell-layer/grid-cell-layer.js
  modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/layers/src/icon-layer/icon-layer.js
  modules/layers/src/line-layer/line-layer.js
  modules/layers/src/path-layer/path-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/scatterplot-layer/scatterplot-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  test/modules/core/lib/layer.spec.js
  test/render/test-cases.js
Labels: code, enhancement

#1930 Remove deprecations: ViewportController and onViewportChange
  dev-docs/RFCs/v5.0/purejs-standalone-rfc.md
  dev-docs/RFCs/vNext/view-state-rfc.md
  docs/api-reference/react/viewport-controller.md
  docs/get-started/using-standalone.md
  docs/upgrade-guide.md
  examples/get-started/pure-js/app.js
  examples/website/point-cloud-laz/app.js
  examples/website/point-cloud-ply/app.js
  examples/website/screen-grid/app.js
  modules/core/src/controllers/controller.js
  modules/core/src/controllers/transition-manager.js
  modules/core/src/deprecated/shaderlib/project/project-deprecated.glsl.js
  modules/core/src/lib/deck.js
  modules/core/src/shaderlib/project/project.js
  modules/main/src/index.js
  modules/react/src/index.js
  modules/react/src/viewport-controller.js
  test/modules/core/lib/transition-manager.spec.js
  website/contents/pages.js
Labels: chore

#1951 Implement RFC: Improved 32-bit LNGLAT projection mode
  docs/upgrade-guide.md
  docs/whats-new.md
  examples/layer-browser/src/examples/core-layers.js
  modules/core/src/lib/constants.js
  modules/core/src/lib/layer.js
  modules/core/src/shaderlib/project/project.glsl.js
  modules/core/src/shaderlib/project/viewport-uniforms.js
  modules/core/src/shaderlib/project32/project32.js
Labels: code, feature

#1977 ScreenGridLayer: Fix cell margin
  modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
  modules/layers/src/screen-grid-layer/screen-grid-layer.js
Labels: bug, enhancement
