Repository visgl/deck.gl, pull requests merged in 2018-03, with the labels that each got.

#1488 Update shader module RFC
  dev-docs/RFCs/README.md
  dev-docs/RFCs/vNext/layer-shader-customization.md
  dev-docs/RFCs/vNext/unified-32-and-64-bit-project-api-rfc.md
Labels: doc

#1491 deck.gl-test-utils: Rename library (#1 of 2)
  docs/api-reference/test-utils/README.md
  examples/test-utils/webpack.config.js
  test/bench/browser.js
  test/bench/core-layers.bench.js
  test/bench/layer.bench.js
  test/bench/node.js
  test/node-aliases.js
  test/render-from-node.js
  test/render/old/test-rendering.react.js
  test/render/test-rendering.js
  test/src/core-layers/core-layers.spec.js
  test/src/core-layers/geojson-layer.spec.js
  test/src/core-layers/grid-cell-layer.spec.js
  test/src/core-layers/grid-layer.spec.js
  test/src/core-layers/hexagon-cell-layer.spec.js
  test/src/core-layers/hexagon-layer.spec.js
  test/src/core-layers/polygon-layer.spec.js
  test/src/core/lib/layer-manager.spec.js
  test/src/core/lib/layer.spec.js
  test/src/core/lib/transition/viewport-fly-to-interpolator.spec.js
  test/src/core/viewports/web-mercator-project-unproject.spec.js
  webpack.config.js
Labels: doc, test

#1485 [Website] Update documentation hierarchy
  website/contents/pages.js
Labels: doc

#1494 Add alpha for minColor to fix test
  test/src/core-layers/core-layers.spec.js
Labels: test

#1500 Modernize tests, remove deprecated test utils
  package.json
  src/test-utils/package.json
  src/test-utils/src/drivers/render-test-driver.js
  src/test-utils/src/index.js
  src/test-utils/src/lifecycle-test-deprecated.js
  src/test-utils/src/lifecycle-test.js
  test/node-dist.js
  test/src/core-layers/core-layers.spec.js
  test/src/core-layers/geojson-layer.spec.js
  test/src/core-layers/grid-cell-layer.spec.js
  test/src/core-layers/grid-layer.spec.js
  test/src/core-layers/hexagon-cell-layer.spec.js
  test/src/core-layers/hexagon-layer.spec.js
  test/src/core-layers/index.js
  test/src/core-layers/polygon-layer.spec.js
  test/src/core/lib/layer.spec.js
  yarn.lock
Labels: code, test

#1499 Update test docs and whats new
  CHANGELOG.md
  docs/api-reference/test-utils/README.md
  docs/api-reference/test-utils/node-test-driver.md
  docs/api-reference/test-utils/render-test-driver.md
  docs/api-reference/test-utils/test-layer.md
  docs/whats-new.md
  src/test-utils/CHANGELOG.md
  src/test-utils/README.md
  website/contents/pages.js
Labels: doc

#1503 change rendering test to react version
  package.json
  test/render/old/test-rendering.react.js
Labels: test

#1515 deck.gl-test-utils v5.2.0-alpha.1
  docs/api-reference/test-utils/README.md
  docs/api-reference/test-utils/scene-renderer.md
  docs/api-reference/test-utils/test-layer.md
  src/test-utils/CHANGELOG.md
  src/test-utils/package.json
Labels: doc

#1517 probe.gl based logging
  aliases.js
  package.json
  src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js
  src/core-layers/hexagon-layer/hexagon-layer.js
  src/core/lib/attribute-manager.js
  src/core/lib/attribute-transition-manager.js
  src/core/lib/composite-layer.js
  src/core/lib/draw-layers.js
  src/core/lib/init.js
  src/core/lib/layer-manager.js
  src/core/lib/layer.js
  src/core/lib/pick-layers.js
  src/core/utils/log.js
  src/core/utils/old-log.js
  src/core/viewports/first-person-viewport.js
  src/core/viewports/orbit-viewport.js
  src/core/viewports/orthographic-viewport.js
  src/core/viewports/perspective-viewport.js
  src/core/viewports/third-person-viewport.js
  src/core/viewports/viewport.js
  src/react/deckgl.js
  src/test-utils/CHANGELOG.md
  src/test-utils/package.json
  yarn.lock
Labels: code

#1518 disable path-marker rendering test
  package.json
  test/render/test-cases.js
Labels: chore

#1464 Update Attribute transitions to use new luma.gl `Transform` API
  src/core/lib/attribute-transition-manager.js
  src/core/lib/attribute-transition-utils.js
Labels: chore

#1411 Update shader module docs
  docs/shader-modules/lighting.md
  docs/shader-modules/project.md
  docs/shader-modules/project64.md
  src/core/shaderlib/lighting/lighting.js
Labels: doc

#1521 Fix minor typo in constants.js
  src/core/lifecycle/constants.js
Labels: chore

#1520 Fix test harness exit code on failure
  package.json
  src/test-utils/package.json
  src/test-utils/src/drivers/render-test-driver.js
  src/test-utils/src/render-test.js
  test/start.js
  yarn.lock
Labels: code

#1524 Reorganize reflection effect PR 1/2
  package.json
  src/core/experimental/reflection-effect/reflection-effect-fragment.glsl.js
  src/core/experimental/reflection-effect/reflection-effect-vertex.glsl.js
  src/core/experimental/reflection-effect/reflection-effect.js
  src/index.js
  yarn.lock
Labels: chore

#1523 Test script consolidation PR 2/2
  aliases.js
  src/test-utils/CHANGELOG.md
  src/test-utils/aliases.js
  src/test-utils/package.json
  src/test-utils/src/drivers/render-test-driver.js
  src/test-utils/src/utils/colors.js
  src/test-utils/test/node-render.js
  src/test-utils/test/node-test-dist.js
  src/test-utils/test/node-test.js
  src/test-utils/test/start.js
  src/test-utils/test/test-browser.js
  src/test-utils/test/test-index.js
  src/test-utils/webpack.config.js
Labels: code, doc

#1477 Example automation testing
  examples/test/golden-images/3d-heatmap.png
  examples/test/golden-images/arc.png
  examples/test/golden-images/bezier.png
  examples/test/golden-images/brushing.png
  examples/test/golden-images/geojson.png
  examples/test/golden-images/graph.png
  examples/test/golden-images/icon.png
  examples/test/golden-images/line.png
  examples/test/golden-images/plot.png
  examples/test/golden-images/scatterplot.png
  examples/test/golden-images/screen-grid.png
  examples/test/golden-images/tagmap.png
  examples/test/golden-images/without-map.png
  package.json
  test/node-examples.js
  yarn.lock
Labels: code, test

#1430 JSAPI: Avoid importing PropTypes in the JavaScript API
  src/core/index.js
  src/core/lib/deck.js
  src/core/pure-js/map-controller-js.js
  src/core/pure-js/orbit-controller-js.js
  src/react/src/deckgl.js
  src/react/src/experimental/orbit-controller.js
  src/react/src/map-controller.js
Labels: code

#1529 Add basic stats collection using probe.gl's Stats class
  .travis.yml
  src/core/lib/attribute-manager.js
  src/core/lib/deck.js
  src/core/lib/draw-layers.js
  src/core/lib/layer-manager.js
  src/core/lib/layer-state.js
  src/core/lib/layer.js
  src/core/lib/stats.js
Labels: code

#1535 Fix max count issue in bin sorter
  src/core/utils/bin-sorter.js
Labels: code

#1534 with-mapbox-map example fix
  examples/experimental/js/with-mapbox-map/app.js
  src/core/lib/layer-manager.js
Labels: code

#1539 Fix bug in getMaxCount
  src/core/utils/bin-sorter.js
Labels: code

#1522 Screen grid colorRange colorDomain
  docs/layers/screen-grid-layer.md
  docs/whats-new.md
  examples/layer-browser/src/examples/core-layers.js
  examples/screen-grid/deckgl-overlay.js
  src/core-layers/screen-grid-layer/screen-grid-layer-vertex.glsl.js
  src/core-layers/screen-grid-layer/screen-grid-layer.js
  src/core/transitions/linear-interpolator.js
  src/core/transitions/transition-utils.js
  src/core/transitions/viewport-fly-to-interpolator.js
  src/core/utils/math-utils.js
  test/render/golden-images/screengrid-lnglat.png
  test/render/test-cases.js
Labels: code

#1545 fix bug in testLayer
  src/test-utils/src/lib/lifecycle-test-deprecated.js
  src/test-utils/src/lib/lifecycle-test.js
  src/test-utils/src/lib/render-test.js
  src/test-utils/src/lib/scene-renderer.js
  src/test-utils/src/lifecycle-test.js
Labels: code

#1557 Implement unified 32 and 64 bit project interface (PR 2/2)
  src/core-layers/arc-layer/arc-layer-vertex-64.glsl.js
  src/core-layers/grid-cell-layer/grid-cell-layer-vertex-64.glsl.js
  src/core-layers/grid-cell-layer/grid-cell-layer-vertex.glsl.js
  src/core-layers/grid-cell-layer/grid-cell-layer.js
  src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex-64.glsl.js
  src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js
  src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js
  src/core-layers/icon-layer/icon-layer-vertex-64.glsl.js
  src/core-layers/icon-layer/icon-layer-vertex.glsl.js
  src/core-layers/icon-layer/icon-layer.js
  src/core-layers/line-layer/line-layer-vertex-64.glsl.js
  src/core-layers/line-layer/line-layer-vertex.glsl.js
  src/core-layers/line-layer/line-layer.js
  src/core-layers/path-layer/path-layer-vertex-64.glsl.js
  src/core-layers/point-cloud-layer/point-cloud-layer-vertex-64.glsl.js
  src/core-layers/point-cloud-layer/point-cloud-layer-vertex.glsl.js
  src/core-layers/point-cloud-layer/point-cloud-layer.js
  src/core-layers/scatterplot-layer/scatterplot-layer-vertex-64.glsl.js
  src/core-layers/scatterplot-layer/scatterplot-layer-vertex.glsl.js
  src/core-layers/scatterplot-layer/scatterplot-layer.js
  src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js
  src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js
  src/core-layers/solid-polygon-layer/solid-polygon-layer.js
Labels: code

#1554 TextLayer: Fix horizontal padding
  src/experimental-layers/src/text-layer/font-atlas.js
Labels: code

#1527 Allow external buffer to be Buffer instead of typed array
  src/core/lib/attribute-manager.js
Labels: code

#1569 Make new colorRange and colorDomain props experimental
  docs/layers/screen-grid-layer.md
  docs/whats-new.md
  examples/layer-browser/src/examples/core-layers.js
  examples/screen-grid/deckgl-overlay.js
  src/core-layers/screen-grid-layer/screen-grid-layer-vertex.glsl.js
  src/core-layers/screen-grid-layer/screen-grid-layer.js
  test/render/golden-images/screengrid-lnglat.png
  test/render/test-cases.js
  test/src/core-layers/core-layers.spec.js
Labels: code, doc, test

#1570 Fix MeshLayer texture rendering
  examples/layer-browser/data/texture.png
  examples/layer-browser/src/examples/experimental-layers.js
  src/experimental-layers/src/mesh-layer/mesh-layer-fragment.glsl.js
  src/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js
  src/experimental-layers/src/mesh-layer/mesh-layer.js
  src/experimental-layers/src/mesh-layer/mesh-layer.md
Labels: code, doc

#1559 Add esnext dist and test-size script
  .babelrc
  .travis.yml
  package.json
  test/scripts/collect-metrics.sh
  test/size/import-nothing.js
  test/webpack.config.js
  yarn.lock
Labels: code, test

#1580 Address `test-utils` audit comments
  docs/advanced/testing.md
  docs/api-reference/test-utils/render-test.md
  src/test-utils/src/drivers/render-test-driver.js
  src/test-utils/src/index.js
  website/contents/pages.js
Labels: chore

#1579 Add metrics to 5.1-release
  .travis.yml
  aliases.js
  package.json
  test/scripts/collect-metrics.sh
  test/size/import-nothing.js
  test/webpack.config.js
  yarn.lock
Labels: chore

#1514 Reorganize "advanced" docs into "Developer Guide"
  docs/advanced/using-standalone.md
  docs/developer-guide/test-utils/README.md
  docs/developer-guide/test-utils/testing.md
  docs/developer-guide/test-utils/using-with-unit-test-frameworks.md
  docs/get-started/using-standalone.md
  docs/get-started/vis-acedemy.md
  website/contents/pages.js
Labels: doc

#1553 Remove `oldProps` and `prevLayers` references
  src/core/lib/layer-manager.js
  src/core/lib/layer.js
Labels: code

#1565 Standalone JS RFC
  dev-docs/RFCs/v5.0/purejs-standalone-rfc.md
Labels: chore

#1573 advanced-text-layer
  examples/layer-browser/src/examples/experimental-layers.js
  src/experimental-layers/src/advanced-text-layer/advanced-text-layer-fragment.glsl.js
  src/experimental-layers/src/advanced-text-layer/advanced-text-layer-vertex.glsl.js
  src/experimental-layers/src/advanced-text-layer/advanced-text-layer.js
  src/experimental-layers/src/advanced-text-layer/advanced-text-layer.md
  src/experimental-layers/src/advanced-text-layer/text-multi-icon-layer.js
  src/experimental-layers/src/index.js
Labels: code, doc

#1567 Remove use of external asserts
  examples/layer-browser/package.json
  package.json
  src/core-layers/geojson-layer/geojson.js
  src/core/controllers/first-person-state.js
  src/core/controllers/map-state.js
  src/core/controllers/orbit-state.js
  src/core/controllers/view-state.js
  src/core/controllers/viewport-controls.js
  src/core/lib/attribute-manager.js
  src/core/lib/attribute-transition-manager.js
  src/core/lib/deck.js
  src/core/lib/draw-layers.js
  src/core/lib/layer-manager.js
  src/core/lib/layer-state.js
  src/core/lib/layer.js
  src/core/lib/pick-layers.js
  src/core/lib/transition-manager.js
  src/core/lifecycle/prop-types.js
  src/core/lifecycle/props.js
  src/core/shaderlib/project/viewport-uniforms.js
  src/core/transitions/linear-interpolator.js
  src/core/transitions/transition-interpolator.js
  src/core/transitions/viewport-fly-to-interpolator.js
  src/core/utils/assert.js
  src/core/utils/math-utils.js
  src/core/utils/old-log.js
  src/core/viewports/viewport.js
  src/core/viewports/web-mercator-viewport.js
  src/core/views/view.js
  src/experimental-layers/src/mesh-layer/mesh-layer.js
  src/test-utils/src/luma.gl/io-basic/browser-compress-image.js
  src/test-utils/src/luma.gl/io-basic/browser-read-file.js
  src/test-utils/src/luma.gl/io-basic/load-files.js
  src/test-utils/src/luma.gl/io-basic/load-texture.js
  src/test-utils/src/luma.gl/io-extended/browser-compress-image.js
  src/test-utils/src/render-test.js
  src/test-utils/src/scene-renderer.js
  yarn.lock
Labels: chore

#1578 Partial Updates #2: Split out `Attribute` class from `AttributeManager`
  docs/api-reference/attribute-manager.md
  src/core/lib/attribute-manager.js
  src/core/lib/attribute.js
  src/experimental-layers/src/mesh-layer/mesh-layer.js
  test/src/core/lib/attribute.spec.js
  test/src/core/lib/index.js
Labels: code, doc, test

#1594 Webpack 4
  package.json
  test/scripts/collect-metrics.sh
  test/webpack.config.js
  yarn.lock
Labels: chore

#1595 Use unified projection in experimental layer shaders
  src/experimental-layers/src/mesh-layer/mesh-layer-vertex-64.glsl.js
  src/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js
  src/experimental-layers/src/mesh-layer/mesh-layer.js
  src/experimental-layers/src/shaderlib/project64utils/project64utils.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js
  src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js
  src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js
  src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
Labels: code

#1596 Unbold console output after test
  test/scripts/collect-metrics.sh
Labels: code

#1590 Move text-layer from experimental-layers to core-layers
  docs/layers/text-layer.md
  examples/layer-browser/src/examples/core-layers.js
  examples/layer-browser/src/examples/experimental-layers.js
  examples/tagmap/tagmap-layer/tagmap-layer.js
  examples/text-layer/deckgl-overlay.js
  src/core-layers/index.js
  src/core-layers/text-layer/font-atlas.js
  src/core-layers/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js
  src/core-layers/text-layer/multi-icon-layer/multi-icon-layer.js
  src/core-layers/text-layer/text-layer.js
  src/experimental-layers/src/index.js
  src/index.js
  test/bench/core-layers.bench.js
  test/render/test-cases.js
  test/src/core-layers/core-layers.spec.js
  test/webpack.config.js
  website/contents/pages.js
Labels: code, test

#1405 Merge experimental SolidPolygonLayer into core-layers
  docs/layers/solid-polygon-layer.md
  examples/layer-browser/src/examples/experimental-layers.js
  src/core-layers/geojson-layer/geojson-layer.js
  src/core-layers/polygon-layer/polygon-layer.js
  src/core-layers/solid-polygon-layer/polygon-tesselator-extruded.js
  src/core-layers/solid-polygon-layer/polygon-tesselator.js
  src/core-layers/solid-polygon-layer/polygon.js
  src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js
  src/core-layers/solid-polygon-layer/solid-polygon-layer.js
  src/experimental-layers/src/index.js
  src/experimental-layers/src/solid-polygon-layer/polygon-tesselator.js
  src/experimental-layers/src/solid-polygon-layer/polygon.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js
  src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js
  test/bench/core-layers.bench.js
  test/bench/tesselation.bench.js
  test/render/golden-images/geojson-extruded-lnglat.png
  test/src/core-layers/polygon-tesselation.spec.js
  test/src/experimental-layers/index.js
  test/src/experimental-layers/polygon-tesselation.spec.js
Labels: code

#1603 ScreenGrid GPU Aggregation (Part-3, Add GPU Aggregation)
  examples/layer-browser/src/data-samples.js
  examples/layer-browser/src/examples/experimental-layers.js
  src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-fragment.glsl.js
  src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-vertex.glsl.js
  src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
  src/experimental-layers/src/utils/gpu-grid-aggregator.js
  test/bench/gpu-grid-aggregator.bench.js
  test/bench/index.js
  test/data/grid-aggregation-data.js
  test/data/index.js
  test/src/experimental-layers/gpu-grid-aggregator.spec.js
  test/src/experimental-layers/index.js
Labels: code

#1611 Hotfix to plot layer and node tests
  src/core/lib/attribute.js
  test/src/core-layers/core-layers.spec.js
Labels: bug
