Repository visgl/deck.gl, pull requests merged in 2019-03, with the labels that each got.

#2688 Update coding guidelines to allow ES2018
  dev-docs/code-guidelines.md
Labels: doc

#2702 integrate lighting effect
  modules/core/package.json
  modules/core/src/effects/lighting-effect.js
  modules/core/src/lib/deck-renderer.js
  modules/core/src/lib/deck.js
  modules/core/src/lib/effect-manager.js
  modules/core/src/lib/effect.js
  modules/core/src/passes/draw-layers-pass.js
  modules/core/src/passes/layers-pass.js
  yarn.lock
Labels: code

#2749 add default lighting and material
  examples/website/geojson/app.js
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
  modules/aggregation-layers/src/grid-layer/grid-layer.js
  modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
  modules/core/package.json
  modules/core/src/effects/lighting-effect.js
  modules/core/src/index.js
  modules/core/src/lib/effect-manager.js
  modules/core/src/shaderlib/lighting/lighting.glsl.js
  modules/core/src/shaderlib/lighting/lighting.js
  modules/geo-layers/src/s2-layer/s2-layer.js
  modules/layers/src/geojson-layer/geojson-layer.js
  modules/layers/src/grid-cell-layer/grid-cell-layer.js
  modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/polygon-layer/polygon-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  modules/lite/test/index.js
  modules/main/src/index.js
  modules/mesh-layers/src/mesh-layer/mesh-layer.js
  test/render/golden-images/first-person.png
  test/render/golden-images/geojson-extruded-lnglat.png
  test/render/golden-images/gpu-grid-lnglat.png
  test/render/golden-images/grid-lnglat.png
  test/render/golden-images/gridcell-lnglat.png
  test/render/golden-images/hexagon-lnglat.png
  test/render/golden-images/hexagoncell-lnglat-64.png
  test/render/golden-images/hexagoncell-lnglat.png
  test/render/golden-images/pointcloud-lnglat-64.png
  test/render/golden-images/pointcloud-lnglat.png
  test/render/golden-images/pointcloud-meter.png
  test/render/test-cases.js
  yarn.lock
Labels: code

#2755 Remove lightSettings prop in examples and website
  examples/experimental/json-common/examples/3d-heatmap.json
  examples/experimental/json-common/examples/geojson.json
  examples/gallery/src/geojson-layer.html
  examples/gallery/src/hexagon-layer.html
  examples/gallery/src/point-cloud-layer.html
  examples/layer-browser/src/examples/additional-layers.js
  examples/layer-browser/src/examples/core-layers.js
  examples/layer-browser/src/examples/infovis-layers.js
  examples/layer-browser/src/examples/perf-layers.js
  examples/website/3d-heatmap/app.js
  examples/website/trips/app.js
  modules/core/package.json
  website/src/components/demos/layer-demos.js
Labels: code

#2756 Change point light class import name
  modules/core/src/effects/lighting-effect.js
Labels: code

#2758 RFC Cleanup
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v6.3/event-handling-rfc.md
  dev-docs/RFCs/v6.3/prop-types-rfc.md
  dev-docs/RFCs/v7.0/composite-layer-customization-rfc.md
  dev-docs/RFCs/v7.0/effects-manager-rfc.md
  dev-docs/RFCs/v7.0/phong-lighting-rfc.md
  dev-docs/RFCs/vNext/layer-intersections-rfc.md
  dev-docs/RFCs/vNext/partial-updates-rfc.md
Labels: chore

#2759 Update probe.gl versions to fix website crash
  package.json
  yarn.lock
Labels: chore

#2762 Add tilt and height to arc-layer
  docs/layers/arc-layer.md
  examples/layer-browser/src/components/layer-controls.js
  examples/layer-browser/src/examples/core-layers.js
  modules/layers/src/arc-layer/arc-layer-vertex.glsl.js
  modules/layers/src/arc-layer/arc-layer.js
Labels: enhancement

#2786 add lighting effect docs
  docs/api-reference/deck.md
  docs/effects/lighting-effect.md
  docs/layers/geojson-layer.md
  docs/layers/gpu-grid-layer.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/hexagon-cell-layer.md
  docs/layers/hexagon-layer.md
  docs/layers/mesh-layer.md
  docs/layers/point-cloud-layer.md
  docs/layers/polygon-layer.md
  docs/layers/solid-polygon-layer.md
  docs/shader-modules/lighting.md
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
  modules/aggregation-layers/src/grid-layer/grid-layer.js
  modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
  modules/layers/src/geojson-layer/geojson-layer.js
  modules/layers/src/grid-cell-layer/grid-cell-layer.js
  modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/polygon-layer/polygon-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  modules/mesh-layers/src/mesh-layer/mesh-layer.js
  website/contents/pages.js
Labels: doc

#2806 integrate phong light module with new name
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
  modules/core/package.json
  modules/core/src/shaderlib/index.js
  modules/layers/src/grid-cell-layer/grid-cell-layer.js
  modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  yarn.lock
Labels: code

#2836 clean up unused code in picking module
  modules/core/src/passes/pick-layers-pass.js
  modules/core/src/utils/pick-info.js
  modules/core/src/utils/query-object.js
Labels: chore

#2835 Update lighting of examples
  examples/website/3d-heatmap/app.js
  examples/website/trips/app.js
  modules/core/src/index.js
Labels: code

#2847 Cleanup unused code
  modules/core/src/lib/effect-preparator.js
  modules/core/src/passes/draw-layers-pass.js
  modules/core/src/passes/layers-pass.js
Labels: chore
