Repository visgl/deck.gl, pull requests merged in 2019-09, with the labels that each got.

#3523 Add Tile3DLayer to geo-layers module
  modules/geo-layers/package.json
  modules/geo-layers/src/index.js
  modules/geo-layers/src/tile-3d-layer/get-frame-state.js
  modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
  modules/main/src/index.js
  yarn.lock
Labels: code

#3553 bump math.gl version
  modules/core/package.json
  modules/core/src/shaderlib/shadow/shadow.js
  modules/core/src/transitions/transition-interpolator.js
  test/apps/multi-viewport/package.json
  test/modules/core/shaderlib/shadow/shadow.spec.js
Labels: code, test

#3564 add rendering test for shadow
  test/render/golden-images/column-shadow-lnglat.png
  test/render/test-cases.js
Labels: test

#3570 fix vricon tile stop rendering issue
  modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
Labels: code

#3595 Add Cesium Ion attributions for 3D tile example
  examples/website/3d-tiles/app.js
  website/src/components/demos/tiles-3d-demo.js
Labels: code

#3596 Update readme and deck.gl dependencies in 3d tiles example
  examples/website/3d-tiles/README.md
  examples/website/3d-tiles/package.json
Labels: doc

#3604 add missing change logs
  CHANGELOG.md
Labels: doc

#3608 Update data for 3D tiles example
  examples/website/3d-tiles/app.js
  website/src/static/images/demo-thumb-3d-tiles.jpg
  website/src/static/markdown/examples.md
Labels: code

#3614 Change API name to _composeModelMatrix for API audit
  modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
  modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
Labels: code

#3677 Fly to Transition auto support
  docs/api-reference/view-state-transitions.md
  modules/core/package.json
  modules/core/src/controllers/transition-manager.js
  modules/core/src/transitions/transition-interpolator.js
  modules/core/src/transitions/viewport-fly-to-interpolator.js
  test/apps/viewport-transitions-flyTo/package.json
  test/apps/viewport-transitions-flyTo/src/app.js
  test/modules/core/lib/transition-manager.spec.js
  test/modules/core/transitions/viewport-fly-to-interpolator.spec.js
  yarn.lock
Labels: feature
