Repository visgl/deck.gl, pull requests merged in 2019-01, with the labels that each got.

#2574 reset blend params after mapbox render
  modules/mapbox/src/deck-utils.js
Labels: bug

#2596 Ib/fix json react example
  examples/experimental/json-react/app.js
  examples/experimental/json-react/index.html
  examples/experimental/json-react/webpack.config.js
Labels: chore

#2637 updated docs with a note about getCursor
  docs/api-reference/deck.md
Labels: doc
