Repository visgl/deck.gl, pull requests merged in 2019-04, with the labels that each got.

#2864 Integrate lighting in mesh layer
  examples/layer-browser/src/app.js
  modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
  modules/core/package.json
  modules/core/src/shaderlib/index.js
  modules/layers/src/column-layer/column-layer.js
  modules/layers/src/point-cloud-layer/point-cloud-layer.js
  modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
  modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.js
  modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.js
  modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
  yarn.lock
Labels: code

#2853 New Lighting docs
  docs/api-reference/lights/ambient-light.md
  docs/api-reference/lights/directional-light.md
  docs/api-reference/lights/point-light.md
  docs/developer-guide/using-lighting.md
  docs/effects/lighting-effect.md
  docs/layers/column-layer.md
  docs/layers/geojson-layer.md
  docs/layers/gpu-grid-layer.md
  docs/layers/grid-cell-layer.md
  docs/layers/grid-layer.md
  docs/layers/h3-hexagon-layer.md
  docs/layers/hexagon-layer.md
  docs/layers/point-cloud-layer.md
  docs/layers/polygon-layer.md
  docs/layers/simple-mesh-layer.md
  docs/layers/solid-polygon-layer.md
  docs/upgrade-guide.md
  website/contents/pages.js
Labels: doc

#2888 switch to babel for examples
  examples/experimental/bezier/package.json
  examples/experimental/bezier/webpack.config.js
  examples/experimental/json-browser/package.json
  examples/experimental/json-browser/webpack.config.js
  examples/get-started/pure-js-without-map/package.json
  examples/get-started/pure-js-without-map/webpack.config.js
  examples/get-started/pure-js/package.json
  examples/get-started/react-webpack-2/package.json
  examples/get-started/react-webpack-2/webpack.config.js
  examples/get-started/react-without-map/package.json
  examples/get-started/react-without-map/webpack.config.js
  examples/website/3d-heatmap/package.json
  examples/website/3d-heatmap/webpack.config.js
  examples/website/arc/package.json
  examples/website/arc/webpack.config.js
  examples/website/brushing/package.json
  examples/website/brushing/webpack.config.js
  examples/website/geojson/package.json
  examples/website/geojson/webpack.config.js
  examples/website/highway/package.json
  examples/website/highway/webpack.config.js
  examples/website/icon/package.json
  examples/website/icon/webpack.config.js
  examples/website/line/package.json
  examples/website/line/webpack.config.js
  examples/website/map-tile/package.json
  examples/website/map-tile/webpack.config.js
  examples/website/plot/package.json
  examples/website/plot/webpack.config.js
  examples/website/point-cloud-laz/package.json
  examples/website/point-cloud-laz/webpack.config.js
  examples/website/point-cloud-ply/package.json
  examples/website/point-cloud-ply/webpack.config.js
  examples/website/scatterplot/package.json
  examples/website/scatterplot/webpack.config.js
  examples/website/screen-grid/package.json
  examples/website/screen-grid/webpack.config.js
  examples/website/tagmap/package.json
  examples/website/tagmap/webpack.config.js
  examples/website/text-layer/package.json
  examples/website/text-layer/webpack.config.js
  examples/website/trips/package.json
  examples/website/trips/webpack.config.js
Labels: chore

#2886 update layer manager doc
  docs/api-reference/internal/layer-manager.md
Labels: chore

#2896 use light type instead of constructor name
  modules/core/src/effects/lighting-effect.js
Labels: code

#2893 Fix ScenegraphLayer attribute problem
  examples/webpack.config.local.js
  modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
Labels: bug

#2944 Move dev scripts out of module roots
  .gitignore
  modules/aggregation-layers/package.json
  modules/core/package.json
  modules/geo-layers/package.json
  modules/google-maps/package.json
  modules/json/package.json
  modules/layers/package.json
  modules/main/package.json
  modules/mapbox/package.json
  modules/mesh-layers/package.json
  scripts/bundle.config.js
Labels: chore

#2943 new camera light feature
  modules/core/src/effects/lighting/camera-light.js
  modules/core/src/effects/lighting/directional-light.js
  modules/core/src/effects/lighting/lighting-effect.js
  modules/core/src/effects/lighting/point-light.js
  modules/core/src/index.js
  modules/core/src/lib/effect-manager.js
  test/modules/core/effects/index.js
  test/modules/core/effects/lighting-effect.spec.js
  test/modules/core/index.js
Labels: code, test

#2959 clean up in mesh layer
  modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
Labels: chore

#2963 Update lighting doc links in website
  docs/api-reference/lights/camera-light.md
  docs/api-reference/lights/directional-light.md
  docs/api-reference/lights/point-light.md
  docs/api-reference/lights/sun-light.md
  docs/effects/lighting-effect.md
  modules/core/src/effects/lighting/sun-light.js
  modules/core/src/index.js
  website/contents/pages.js
Labels: doc

#2982 fix effects comparing issue
  modules/core/src/lib/effect-manager.js
Labels: code

#2984 Fix screen grid layer crash in safari
  modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-vertex-webgl1.glsl.js
Labels: code

#2990 replace getStrokeWidth with getWidth
  examples/website/line/app.js
  website/src/components/demos/layer-demos.js
  website/src/components/demos/line-demo.js
Labels: code

#2996 fix gpu grid layer link
  website/contents/pages.js
Labels: code

#2997 Remove deprecated APIs and update doc
  docs/layers/screen-grid-layer.md
  modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
  modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
  website/contents/pages.js
  website/src/components/demos/aggregation-layer-demos.js
Labels: code, doc

#2998 fix website warnings
  docs/developer-guide/custom-layers/subclassed-layers.md
  examples/website/plot/plot-layer/axes-layer.js
  examples/website/plot/plot-layer/surface-layer.js
  examples/website/trips/app.js
  website/src/components/demos/layer-demos.js
Labels: code, doc

#2999 Fix buffer warnings
  modules/core/src/lib/base-attribute.js
Labels: chore

#3002 improve babel config for Edge/IE
  website/package.json
  website/webpack.config.js
Labels: code

#3036 update what's new for lighting
  docs/whats-new.md
Labels: doc

#3040 add gif images to light source docs
  docs/api-reference/lights/ambient-light.md
  docs/api-reference/lights/camera-light.md
  docs/api-reference/lights/directional-light.md
  docs/api-reference/lights/point-light.md
Labels: doc

#3047 update internal props of point lights
  modules/core/src/effects/lighting/camera-light.js
  modules/core/src/effects/lighting/point-light.js
  test/modules/core/effects/lighting-effect.spec.js
Labels: chore
