Repository visgl/deck.gl, pull requests merged in 2019-02, with the labels that each got.

#2656 Refactor rendering workflow (1/3)
  modules/core/src/lib/deck-renderer.js
  modules/core/src/lib/layer-manager.js
  modules/core/src/passes/draw-layers-pass.js
  modules/core/src/passes/layers-pass.js
  modules/core/src/passes/pass.js
  modules/core/src/passes/pick-layers-pass.js
  yarn.lock
Labels: code

#2671 Merge rendering refactor(2/3) to right feature branch
  modules/core/src/effects/effect-manager.js
  modules/core/src/effects/effect.js
  modules/core/src/effects/lighting-effect.js
  modules/core/src/lib/deck-renderer.js
Labels: chore

#2668 Remove IO functions (moved to loaders.gl)
  modules/test-utils/src/index.js
  modules/test-utils/src/luma.gl/gpgpu/index.js
  modules/test-utils/src/luma.gl/io-basic/README.md
  modules/test-utils/src/luma.gl/io-basic/browser-compress-image.js
  modules/test-utils/src/luma.gl/io-basic/browser-read-file.js
  modules/test-utils/src/luma.gl/io-basic/browser-request-file.js
  modules/test-utils/src/luma.gl/io-basic/browser-request-image.js
  modules/test-utils/src/luma.gl/io-basic/index.js
  modules/test-utils/src/luma.gl/io-basic/json-loader.js
  modules/test-utils/src/luma.gl/io-basic/load-files.js
  modules/test-utils/src/luma.gl/io-basic/load-texture.js
  modules/test-utils/src/luma.gl/io-basic/node-compress-image.js
  modules/test-utils/src/luma.gl/io-basic/node-load-image.js
  modules/test-utils/src/luma.gl/io-basic/path-prefix.js
  modules/test-utils/src/luma.gl/io-extended/README.md
  modules/test-utils/src/luma.gl/io-extended/browser-compress-image.js
  modules/test-utils/src/luma.gl/io-extended/browser-write-file.js
  modules/test-utils/src/luma.gl/io-extended/index.js
  modules/test-utils/src/luma.gl/io-extended/test/index.js
  modules/test-utils/src/luma.gl/io-extended/test/write-read-image.spec.js
  modules/test-utils/src/luma.gl/test/index.js
  modules/test-utils/src/luma.gl/test/read-image.spec.js
  modules/test-utils/src/render-test.js
  modules/test-utils/src/scene-renderer.js
  modules/test-utils/src/utils/deprecated/browser-image-utils.js
  modules/test-utils/src/utils/deprecated/diff-images.js
  modules/test-utils/src/utils/deprecated/globals.js
  modules/test-utils/src/utils/deprecated/headless.js
  modules/test-utils/src/utils/setup-gl.js
Labels: chore

#2689 Refactor picking workflow (1/2)
  examples/layer-browser/src/app.js
  modules/core/src/lib/deck-picker.js
  modules/core/src/lib/layer-manager.js
  modules/core/src/lib/picking/pick-info.js
  modules/core/src/lib/picking/query-object.js
  modules/core/src/utils/get-pixel-ratio.js
Labels: code

#2690 Refactor picking workflow (2/2)
  modules/core/src/lib/deck-picker.js
  modules/core/src/lib/deck-renderer.js
  modules/core/src/lib/deck.js
  modules/core/src/lib/layer-manager.js
  modules/core/src/lib/layer.js
  modules/core/src/utils/pick-info.js
  modules/core/src/utils/pixel-ratio.js
  modules/core/src/utils/query-object.js
Labels: code

#2699 fix broken picking API bench test
  test/bench/pick-layers.bench.js
  test/bench/tesselation.bench.js
Labels: test
